### ISSUE TITLE
sleep command does not allow variables 

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#74]
it seems like seconds in sleep-commands currently only work with integer:

```yaml
 - type: sleep
    seconds: "$MAX_SEC"
    min_sec: 15
    random: True
```

```
Traceback (most recent call last):
  File "/usr/local/share/attackmate/venv/bin/attackmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/share/attackmate/venv/lib/python3.10/site-packages/attackmate/__main__.py", line 163, in main
    hacky = AttackMate(parse_playbook(args.playbook, logger), parse_config(args.config, logger))
  File "/usr/local/share/attackmate/venv/lib/python3.10/site-packages/attackmate/__main__.py", line 127, in parse_playbook
    playbook_object = Playbook.parse_obj(pb_yaml)
  File "/usr/local/share/attackmate/venv/lib/python3.10/site-packages/pydantic/main.py", line 1118, in parse_obj
    return cls.model_validate(obj)
  File "/usr/local/share/attackmate/venv/lib/python3.10/site-packages/pydantic/main.py", line 551, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Playbook
vars.MAX_SEC
  Input should be a valid string [type=string_type, input_value=380, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
```

**Comment by whotwagner** [comment]
Not a bug, just wrong indentation
